# Generated by Django 2.1.7 on 2019-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
