# Generated by Django 2.1.7 on 2019-04-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0005_add_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='image',
        ),
    ]
