# Generated by Django 2.1.7 on 2019-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0006_remove_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
