# Generated by Django 2.1.7 on 2019-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0007_add_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
